### ISSUE TITLE
Questions about randomly set delta parameters==zero

### ISSUE THREAD

**Issue by Fay-why** [yule-BUAA/MergeLM#26]
Dear author, thanks for your work.

I noticed that in your paper, you randomly set p% delta parameters to zero. The Theoretical Analysis section guarantees that the expectation of origin SFT equals the expectation of DARE after randomly set some parameters and rescale the other parameters.

I wonder if there are additional problems with just expectation equality. For example, by randomly erasing some parameters that are important for downstream tasks, because according to the paper, DARE can erase 90% of the delta parameters.

**Comment by yule-BUAA** [comment]
Hi,

Thanks for your interest in our work.

Firstly, please note that DARE  is applicable to SFT models with delta parameters within a range of 0.005. Therefore, the impact of eliminating a large portion of slightly changed delta parameters can be offset by correspondingly amplifying the remaining parameters. This is in line with our theoretical analysis, which points out DARE can ensure that the output of each layer of the model after parameter deletion remains close to that of the original model. However, when the range of delta parameter variation expands further (for example, to 0.03), the effectiveness of DARE is significantly reduced (as seen in Section 4.6).

Secondly, it is possible that there exist "important" parameters for downstream tasks. For instance, the sharp decline in performance of WizardLM-70B when the drop rate is 0.9 (as shown in Figure 12 (a)) could be due to this reason. However, such situations occur infrequently. The primary reason is that DARE currently focuses on models where the range of delta parameters is relatively small, reducing the probability of parameters becoming important due to their large degree of change.

I hope this clarifies your issue. Please feel free to reach out if you have any further questions.

**Comment by yule-BUAA** [comment]
Close this issue now.

Feel free to reopen it if there are any further questions.
