### ISSUE TITLE
When getting Figure3, and 4, you apply DARE on all layer seperately?

### ISSUE THREAD

**Issue by yuang-lee** [yule-BUAA/MergeLM#38]
Nice work!
Want to check when you run experiments for Figure3, and 4, did you apply DARE on every model's layer/matrix separately or did you flatten them to a long single vector then apply DARE?

Thanks!

**Comment by yule-BUAA** [comment]
Hi,

For all the experiments, including those depicted in Figures 3 and 4, DARE was applied to each model's matrix separately to ensure efficient implementation. You can refer to the implementation details [here](https://github.com/yule-BUAA/MergeLM/blob/6d49ad96fd69c92013654b837041b868aa806564/model_merging_methods/mask_weights_utils.py#L64). Please be aware that due to the random drop operation in DARE, applying DARE to either separate matrices, individual layers, or the entire model should yield similar results.

**Comment by yuang-lee** [comment]
Thanks for your reply! It's really helpful.
Another question: When integrating with TIES, which of the following is the correct order?
1. Apply DARE on task vectors first, then TIES (Trim, Elect Sign, Disjoint merge)
2. Apply Trimming on task vectors, then DARE, Elect Sign, Disjoint merge

I suppose it's 1. ? 
would be really grateful for your answer, thanks

**Comment by yule-BUAA** [comment]
Yes! 

Your understanding is correct.

For DARE + TIES, we first use DARE to sparsify the task vectors and then apply TIES.
Please note that the Trim operation in TIES becomes unnecessary when the trim rate in TIES is equal to or less than the drop rate in DARE. This is because DARE resets the delta parameters to zeros and TIES trims delta parameters with the smallest magnitudes, which are exactly the zeros reset by DARE.
