### ISSUE TITLE
What is the LICENSE type of this repo?

### ISSUE THREAD

**Issue by ramkumarkoppu** [yule-BUAA/MergeLM#8]
What is the LICENSE type of this repo?

**Comment by yule-BUAA** [comment]
Hello,

All the resources we use are publicly available and this repository does not introduce new models or datasets. So, the LICENSE types of the used models or datasets are identical to their original ones (e.g., apache-2.0 for bert-base-uncased, it for roberta-base, Non-commercial or Llama 2 for WizardLM series models).

For the proposed DARE algorithm, I think it can be widely used under the MIT License.

I will update the LICENSE information latter.

**Comment by yule-BUAA** [comment]
Close this issue now.

Please feel free to reopen it when there are any further questions.

**Comment by mbrukman** [comment]
@yule-BUAA -- maybe I missed it, but I didn't notice a `LICENSE` file at the top of the repo tree. Did you happen to add it somewhere else by chance?

In case it's not there yet, since you said it should be under the MIT license, you can find that license here: https://choosealicense.com/licenses/mit/ so it would be easy to add.

Thanks!
